config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks
  
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user

	has_attached_file :photo, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :task
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name,:last_name, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name,:last_name, :email, :password, :current_password) }
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authenticate_user! , except: [:index,:show]
    
  def index
    if user_signed_in?
      @tasks=Task.where({created_by:current_user.id,active:true}).order(event_time: :asc)
    else
      @tasks=Task.where({active:true})
    end
  end

  def show
      @task = Task.find(params[:id])
      @createdby=User.find(@task.created_by)

  end

  def new
    @task=Task.new
  end

  def create
    @task=Task.create(task_params)
    @task.created_by=current_user.id
    
    if @task.save
      flash[:notice] = "Post successfully created"
      redirect_to tasks_path
    else
      render 'new'
    end
  end


  def edit
    @task=Task.find(params[:id])

  end

  def update
      @task=Task.find(params[:id])
    
      if @task.update_attributes(task_params)
        flash[:notice] = "Task successfully updated"
        redirect_to tasks_path
      else
        render 'edit'
      end
  end

  def destroy
  @task =Task.find(params[:id])
  @task.destroy

  redirect_to tasks_path
  end

  private 
  def task_params
    params.require(:task).permit(:title,:active,:photo,:user_id,:event_time,:created_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> 
  <%= csrf_meta_tags %>
</head>
<body class="backboard img-responsive"> 

<div class="row">
  <nav class="navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
       
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
       

         <!--<a class="navbar-brand" href="#">Brand</a>-->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <div class="col-md-3">
        <ul class="nav navbar-nav">
          <li>    
            <%if user_signed_in?%>
                <label><%= link_to "Create New", new_task_path, :class=>"logged" %></label> 
            <%end%>
          </li>

        </ul>
        </div>
      
       <div class="col-md-6 col-sm-9">
        
            <label><i>
                <%= link_to "Simple ... TO DO ... ", tasks_path, :class=>"navbar-brand logged brand" %>
              </i></label>
        </div>
      
      <div class="col-md-3">
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        		<li>

            <label class="logged"> Welcome <%= current_user.first_name.capitalize %> </label></li>
            <li>    
            <label class="logged"><%= link_to "Log Out",destroy_user_session_path, :method => :delete %> </label></li>

            </li>
        	<% else %>
        		<li><%= render 'devise/sessions/new' %></li>
          <% end %>
              
            </ul>
          </li>
        </ul>
        </div>


      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  </div>
<div class="row">
      <div class="text-center">
		   <label class="logged"> <%= flash[:alert] %>
		  <%= flash[:notice] %></label> 
	  </div>

       <!--<span class="notice"><%= notice %></span>-->
       <!--<span class="alert"><%= alert %></span>-->
      </div>
</div>
  <div class="row" style="width: 100%;">
    <div class=" col-md-10 col-md-offset-1">

      <%= yield %>
    </div>
  </div>  
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html =>{:multipart => true} do |f| %>
	<div class="col-md-6 label30">
		<%= f.label :event_time  %><br>
		<%= f.text_field :event_time, :class =>"form-control" %><br>		

		<%= f.label :title  %><br>
		<%= f.text_field :title, :class =>"form-control" %><br>
		

		<%= f.label :photo %><br>
		<%= f.file_field :photo, :class =>"form-control"  %><br>
		<div class="row">
			<div class="col-md-4">
					<%= f.label "Assigne to" %><br>
			</div>
			<div class="col-md-4">
					<%= f.label :active %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<%= f.collection_select :user_id, User.all, :id, :first_name ,:class =>"form-control"%><br><br>
			</div>
			<div class="col-md-4">
				<%= f.check_box :active %><br><br>
			</div>
			<div class="col-md-4">
				<%= f.submit "SAVE", :class =>"btn btn-default btn-lg pull-right" %>
			</div>
		</div>
	</div>
<%end%>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<div class="col-md-offset-1 form-group marginLeft36">
	<h2>EDIT TASK</h2>
	<%= render 'form'%>
</div>

app/views/tasks/index.html.erb
<div class="row" style="    height: 1100px;">
  <div class="col-md-12 pull-right">
  <% @tasks.each do |task| %>
		  <div class="col-md-2 notebox top60">

			<%= link_to (image_tag task.photo.url(:medium)), task %>

	        
	          	<% if task.title? %>
		          	<%= link_to(task) do %>
		          		<% if task.event_time?%>
				      		<label class="tasktime"><%= task.event_time.strftime('%D %H:%M') %></label><br>
				      	<%end %>  
			          	<% if task.title.length >=16 %>
				      		<label class="tasktitile"><%= task.title.truncate(16)+".." %></label><br>
				      	<% else %>
							<label class="tasktitile"><%= task.title %></label><br>
				      	<% end%>
     			
				      	<% if user_signed_in?  && current_user.id==task.created_by %>
	      					<span><%= link_to "Edit", edit_task_path(task), :class =>"btn btn-default noteedit"%></span>
	      					<span>
	      					<%= link_to "delete", task_path(task), method: :delete,
                                  data: { confirm: "You sure?" } , :class =>"btn btn-default notedelete"%>
							</span>


      					<% end %>
	      	   	<%end %>
		      



		      <% end %>

		  </div>
	  <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="col-md-offset-1 form-group top60 marginLeft36">
	<h2>NEW TASK</h2>
	<%= render 'form'%>
</div>

app/views/tasks/show.html.erb
<div class="col-md-offset-1 col-md-10 ">
			
	<div class="form-group show">
			<%= link_to (image_tag @task.photo.url(:medium),:class => "img-responsive center-block"), @task %>
			
			<div class="showtext">
				<h1><b>Title:</b> <%= @task.title %></h1>

				<h1><b>Assigned To:</b>  <%= @task.user.first_name %>  <%= @task.user.last_name %></h1>

				<h1><b>Event Time:</b> <%= @task.event_time %></h1>

				<h1><b>Created By:</b> <%=  @createdby.first_name %> <%= @createdby.last_name %></h1>
			</div>
	</div>
</div>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>